from backend.services import extract_latest_fiscal_year, extract_metrics, extract_revenue_history

SAMPLE_10K_TEXT = """
For the fiscal year ended September\xa027, 2025

Common Stock, $0.00001 par value per share

Segment revenue
Americas
$
178,353
6 % $
167,045

Total net sales
$
416,161
6 % $
391,035

Total net sales
416,161
391,035
383,285

Net income
$
112,010

Total assets
$
359,241

Total current liabilities
165,631
Total liabilities
285,508
Total liabilities and shareholders' equity
$
359,241

Adjustments to reconcile net income to cash generated by operating activities:
Depreciation and amortization
11,698

Cash generated by operating activities
111,482
"""


def test_extract_metrics_prefers_totals_over_segment_and_footnote_figures() -> None:
    metrics = extract_metrics(SAMPLE_10K_TEXT)
    assert metrics.revenue == 416161
    assert metrics.net_income == 112010
    assert metrics.assets == 359241
    assert metrics.liabilities == 285508
    assert metrics.operating_cash_flow == 111482


def test_extract_revenue_history_skips_percent_change_tables() -> None:
    assert extract_revenue_history(SAMPLE_10K_TEXT) == [383285, 391035, 416161]


def test_extract_latest_fiscal_year_handles_nonbreaking_space() -> None:
    assert extract_latest_fiscal_year(SAMPLE_10K_TEXT) == 2025
